### ISSUE TITLE
Restructure Code - serperate applications from Lib

### ISSUE THREAD

**Issue by vogt31337** [beanit/openiec61850#8]
Hi,

I like your library, but I would encourage you to seperate your applications (demo server / client) from your library code.
Maybe create a new Project? Add some tools for debugging purpose?

BR

**Comment by sfeuerhahn** [comment]
thanks for your feedback.

the application (which I consider only a small supplement to the library) used to be a separate project but I saw no benefits in that.

What would be the benefits in your opinion?

**Comment by bmhm** [comment]
Hi, sorry for off-topic. @vogt31337  can you please take a look at https://github.com/java-native/jssc/issues/39? I know you worked on `java-simple-serial-connector` but I saw now other way to contact you. I will delete this comment in a few days. Sorry again for stealing this issue for this!
